# Generated by Django 6.1.2 on 2026-10-08 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('event_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JunctionState',
            fields=[
                ('junction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='traffic.junction')),
                ('mode', models.CharField(default='AUTOMATIC', max_length=20)),
                ('phase', models.CharField(default='NORTH_SOUTH', max_length=20)),
                ('stage', models.CharField(default='GREEN', max_length=20)),
                ('desired_signals', models.JSONField(default=dict)),
                ('actual_signals', models.JSONField(default=dict)),
                ('emergency', models.JSONField(blank=True, null=True)),
                ('manual', models.JSONField(blank=True, null=True)),
                ('controller_status', models.CharField(default='ONLINE', max_length=20)),
                ('stage_started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('detail', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('junction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.junction')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PendingCommand',
            fields=[
                ('command_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=10)),
                ('requested_state', models.CharField(max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('junction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.junction')),
            ],
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=10)),
                ('vehicle_id', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=30)),
                ('arrived_at', models.DateTimeField()),
                ('sequence_no', models.IntegerField(blank=True, null=True)),
                ('junction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.junction')),
            ],
            options={
                'unique_together': {('junction', 'vehicle_id')},
            },
        ),
    ]
